// Generated by: npx supabase gen types typescript --linked > src/types/supabase.ts
// Run that command after applying migrations. This stub satisfies the import
// until the real schema types are generated.
export type Database = Record<string, never>;
